# iloc vs loc

**iloc**: Purely integer-location based indexing for selection by position.

**loc:** Purely label-location based indexer for selection by label.

In [3]:
import pandas as pd
 
df = pd.DataFrame({'Age': [30, 20, 22, 40, 32, 28, 39],
                   'Color': ['Blue', 'Green', 'Red', 'White', 'Gray', 'Black',
                             'Red'],
                   'Food': ['Steak', 'Lamb', 'Mango', 'Apple', 'Cheese',
                            'Melon', 'Beans'],
                   'Height': [165, 70, 120, 80, 180, 172, 150],
                   'Score': [4.6, 8.3, 9.0, 3.3, 1.8, 9.5, 2.2],
                   'State': ['NY', 'TX', 'FL', 'AL', 'AK', 'TX', 'TX']
                   },
                  index=['Jane', 'Nick', 'Aaron', 'Penelope', 'Dean',
                         'Christina', 'Cornelia'])

In [6]:
df.iloc[0:2,0:2]

Age  Color
Jane   30   Blue
Nick   20  Green

In [7]:
df.loc[["Jane", "Nick"], ["Age", "Color"]]

Age  Color
Jane   30   Blue
Nick   20  Green

In [15]:
df["Age"] # == df.loc[:,"Age"]

Jane         30
Nick         20
Aaron        22
Penelope     40
Dean         32
Christina    28
Cornelia     39
Name: Age, dtype: int64

In [13]:
df.iloc[0] # == df.loc[Jane]

Age          30
Color      Blue
Food      Steak
Height      165
Score       4.6
State        NY
Name: Jane, dtype: object

In [16]:
df.loc[:,"Age"]

Jane         30
Nick         20
Aaron        22
Penelope     40
Dean         32
Christina    28
Cornelia     39
Name: Age, dtype: int64

# Indexing

Prozess um eine Teilmenge zu extrahieren. Charakteristisch sind die eckigen Klammern.

In [20]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

# Difference between fit and fit_transform in scikit_learn models?

In [80]:
from sklearn.preprocessing import StandardScaler;
data = np.reshape(range(0,10), (-1, 2)) # == np.reshape(range(0,10),(-1,2))
display(data)
scaler = StandardScaler(copy=True, with_mean=True, with_std=True);
scaler.fit(data); # berechnet nur die Standardabweichung und den Mittelwert
featureValues_std = scaler.transform(data); # führt die Transformation durch
display(featureValues_std)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

array([[-1.41421356, -1.41421356],
       [-0.70710678, -0.70710678],
       [ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356]])

In [89]:
data.mean(axis=0) 

array([4., 5.])

In [91]:
data.std(axis=0)

array([2.82842712, 2.82842712])

In [101]:
(data[0,0] - 4 ) / 2.82842712 # aufpassen data ist ein numpy array daher indexiere ich via [0,0] oder via [0][0] und nicht via iloc[0,0]

-1.41421356474619